from typing import Annotated, Sequence
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from langchain_openai import ChatOpenAI
from defiagents.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    risky_history: Annotated[
        str, "Risky Agent's Conversation history"
    ]  # Conversation history
    safe_history: Annotated[
        str, "Safe Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_risky_response: Annotated[
        str, "Latest response by the risky analyst"
    ]  # Last response
    current_safe_response: Annotated[
        str, "Latest response by the safe analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    # DeFi-specific parameters
    protocol_of_interest: Annotated[str, "DeFi protocol that we are interested in analyzing"]
    chain: Annotated[str, "Blockchain network (ethereum, arbitrum, optimism, etc.)"]
    investment_amount: Annotated[Optional[float], "Investment amount in USD for strategy analysis"]
    protocol_whitelist_status: Annotated[
        Optional[str], "Result status from protocol whitelist validation"
    ]
    whitelist_result: Annotated[
        Optional[dict], "Full whitelist result payload for downstream consumers"
    ]
    trade_date: Annotated[str, "What date we are analyzing at"]

    # Legacy compatibility (deprecated, use protocol_of_interest instead)
    company_of_interest: Annotated[Optional[str], "DEPRECATED: Use protocol_of_interest"]

    sender: Annotated[str, "Agent that sent this message"]

    # Analyst reports
    market_report: Annotated[str, "Report from the DeFi Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current DeFi affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Protocol Analyst"]
    yield_report: Annotated[str, "Report from the Yield Analyst"]
    risk_report: Annotated[str, "Report from the DeFi Risk Analyst"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
